#lang scheme

; Draw the tree illustrating the process generated by the count-change procedure
; of 1.2.2 in making change for 11 cents.

; What are the orders of growth of the space and number of steps
; used by this process as the amount to be changed increases?

;                                  (count-change 11)
;                                         |
;                                  _____(cc 11 5)______
;                                 /                    \
;                        ____(cc 11 4)__________    (cc -39 5)
;                       /                       \
;             ______(cc 11 3)__________________ (cc -14 4)
;            /                                 \
;    _____(cc 11 2)_____                  _____(cc 1 3)_____
;   /                   \                /                  \
; (cc 11 1)           (cc 6 2)         (cc 1 2)            (cc -9 2)

; and so on...

; orders of growth of space -- O(n) because depth will be atmost n.
; orders of growth of steps -- n^k, n amount and k coins

